import express from "express";
import { exec } from "child_process";
import fs from "fs";

const app = express();
const PORT = 3000;

// Serve public files
app.use(express.static("public"));

// API to get sales
app.get("/api/sales", (req, res) => {
  let sales = [];
  if (fs.existsSync("./sales.json")) {
    try {
      // Attempt to read and parse the JSON file
      const fileContent = fs.readFileSync("./sales.json", "utf-8");
      // Ensure the file is not empty before parsing
      if (fileContent) {
        sales = JSON.parse(fileContent);
      }
    } catch (error) {
      // If parsing fails, log the error and continue with an empty array.
      // This prevents the server from crashing due to a corrupt file.
      console.error("Error parsing sales.json:", error.message);
      console.log("The sales.json file is corrupt or empty. A new file will be generated by the scraper.");
      sales = [];
    }
  }
  res.json(sales);
});

// Start server
app.listen(PORT, () => {
  console.log(`✅ Dashboard running at http://localhost:${PORT}`);

  // Start the scraper
  const scraper = exec("node vinted.js");

  scraper.stdout.on("data", (data) => console.log(data.toString()));
  scraper.stderr.on("data", (data) => console.error(data.toString()));
});
