import express from "express";
import cors from "cors"; // 1. Import the cors package
import { spawn } from "child_process";
import fs from "fs";
import path from "path";

const app = express();
const PORT = 3000;
const SALES_FILE = path.join(process.cwd(), "mens.json");

// ** 2. Use the cors middleware **
// This will allow your domain to make requests to the API.
app.use(cors());

// Serve public files from the 'public' directory
app.use(express.static("public"));

// API endpoint to get sales data
app.get("/api/sales", (req, res) => {
  let sales = [];
  try {
    if (fs.existsSync(SALES_FILE)) {
      const fileContent = fs.readFileSync(SALES_FILE, "utf-8");
      if (fileContent) {
        sales = JSON.parse(fileContent);
      }
    }
  } catch (err) {
    console.error("Error parsing sales.json:", err.message);
    console.warn("The sales.json file is corrupt or empty. A new file will be generated by the scraper.");
  }
  res.json(sales);
});

// Start the Express server
app.listen(PORT, () => {
  console.log(`✅ Dashboard running at http://localhost:${PORT}`);
  
  const scraper = spawn('node', ['mens.js'], {
    detached: true,
    stdio: 'inherit'
  });

  scraper.unref();

  console.log("🚀 Vinted scraper process has been started.");
});

